server:
  port: 8085

spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shop}
    username: ${SPRING_DATASOURCE_USERNAME:shop}
    password: ${SPRING_DATASOURCE_PASSWORD:shop}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        default_schema: users
        hbm2ddl:
          create_namespaces: true
